name: run all tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  local_tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: run all tests
        run: python3 autoop/tests/main.py