name: Style check

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  local_tests:
    permissions: write-all
    runs-on: prroai
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: run all tests
        run: python -m autoop.tests.main